addon/components/positioned-container.js
Be a good citizen!
Courtesy of your friendly neighborhood Ember NYC Project Night Improve-an-addon contingent!
=> Use Ember.observer and Ember.on instead of function prototype equivalents

bower.json, package.json
It's old and it generates warnings in ember-cli.
=> Drop unused ember-data dependency

.travis.yml, config/ember-try.js, package.json
This enables parallel travis test runs for each of ember 1.10, 1.11, beta, and canary.
Canary is marked with `allow_failures` for now, so it is only advisory and won't cause the overall test run to fail.
=> Test against 1.10 through beta

README.md
maybe it was just me? when I quickly glanced at key-responder the verbiage was abstract enough that I didn't understand it was about keyboard events/shortcuts
=> Clarify key-responder is about keyboard shortcuts

app/components/ember-modal-dialog-overlay.js
In 5802c696333718f7b1268d40962b8a8974c4e688, the referenced file in this component was deleted. This revision deletes the corresponding orphan file.
=> Remove orphan overlay component

package.json
In reference to this issue: https://github.com/ember-cli/ember-cli/issues/3489. Building and serving causes an ETIMEDOUT error. Upgrading to latest to fix this.
=> Updating ember-cli version to fix build errors on windows

README.md, addon/components/modal-dialog.js, addon/components/positioned-container.js, addon/templates/components/modal-dialog.hbs, examples/custom-styles.hbs, examples/subclass.hbs, examples/subclass.js, tests/acceptance/modal-dialogs-test.js, tests/dummy/app/components/my-cool-modal-dialog.js, tests/dummy/app/styles/app.scss, tests/dummy/app/templates/application.hbs
This commit reworks how css classes are provided to the modal-dialog component
and then handed down to the overlay div and the position-container component.
Previously, we attempted to use one property for both template-provided css
classes as well as subclass-provided css classes. That is problematic for the
same reason that Ember separates classNames and classNameBindings. After this
commit, if you want to specify additional class name(s) when you are using
`modal-dialog` in a hbs template, use `overlay-class` and/or
`container-class`, and if you want to specify additional class names(s) when
you are subclasses the `modal-dialog` component, use `overlayClassNames`
and/or `containerClassNames`. The dummy app has been updated with examples.
=> Introduced overlay-class and container-class attributes.

addon/components/modal-dialog.js, addon/templates/components/modal-dialog.hbs, tests/acceptance/modal-dialogs-test.js
Add a css class to the positioned div of the form `ember-modal-dialog-[alignment]`, to make applying css based on alignment easier.
=> Add an alignment css class to the positioned div

addon/components/modal-dialog.js, addon/templates/components/modal-dialog.hbs, app/styles/ember-modal-dialog/ember-modal-structure.scss, examples/in-place.hbs, package.json, tests/acceptance/modal-dialogs-test.js, tests/dummy/app/controllers/application.js, tests/dummy/app/initializers/register-subclassed-modals.js, tests/dummy/app/styles/app.scss, tests/dummy/app/templates/application.hbs
=> Wormhole-less Modals

README.md, addon/components/modal-dialog.js, addon/initializers/add-modals-container.js, addon/services/modal-dialog.js, app/services/modal-dialog.js
=> Add modal-dialog service with `destinationElementId` for easier subclassing

addon/initializers/add-modals-container.js
Prior to adding this guard, any applications using fastboot would throw an error on application boot (because `document` is `undefined` in Node).
The modal dialog behavior in this addon will likely not work, but the application should boot.
=> Guard against `document` being undefined.

README.md
This is to address issue #24. Currently the documentation doesn't specify how and when the modal's `close` action is triggered, which has caused some confusion for users.
=> Clarifies the close action's functionality in the documentation

index.js, package.json
For a few reasons the `semver.satisfies` function does not match
prelease versions in the same way as we want (it does make sense
though).
See https://github.com/npm/node-semver#prerelease-tags.
This PR switches over to use the simpler `gt`/`lt` methods which behaves
much more like what we need with prerelease versions.
A few examples using `semver.lt`:
```
> semver.lt('1.12.0-beta.1', '1.13.0')
true
> semver.lt('1.13.0-beta.1', '1.13.0')
true
> semver.lt('1.12.0', '1.13.0-beta.1')
true
> semver.lt('2.0.0', '1.13.0-beta.1')
false
> semver.lt('1.13.0', '1.13.0-beta.1')
false
> semver.lt('1.13.0-beta.1', '1.13.0-beta.1')
false
```
---
Thanks to @ef4 for pointing this out!
=> Allow 2.0.0-beta's to use current templates.

README.md, addon/components/modal-dialog.js, tests/acceptance/modal-dialogs-test.js, tests/acceptance/modal-dialogs-without-tether-test.js, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/application.hbs, tests/helpers/modal-asserts.js
The result of #55. The use case is treating the modal as a glorified tooltip where it not necessarily the focus of attention, nor the center of the screen. Now you can have the functionality of clicking off closes, while retaining mouse effects like link hovering/clicking and other hover effects.
=> Adds the ability to close when clicking anywhere outside the modal without an overlay

addon/components/positioned-container.js
If alignmentTarget selector doesn't specify an existing element, almost certain to cause an error further down (e.g. call on undefined originOffset).  This assert  points out  the source of the problem.
=> assert that specified alignment target exists

tests/dummy/app/styles/app.scss
Disabling overflow[1] other scrolling panes, e.g. `<body>`, will make it easier to scroll the modal, but it's no hard requirement. This is true for any situation where multiple 'layers' are scrollable.
[1] `overflow-y: hidden`
=> Make centered scrolling example work

addon/initializers/add-modals-container.js
In ember 2.1 apps we get a dep warning about the changes to initializers. This change will support older and newer ember apps
=> Made the initializer ember 1.13/2.0/2.1 friendly

.jscsrc, addon/components/modal-dialog.js, addon/components/positioned-container.js, addon/components/tether-dialog.js, tests/acceptance/modal-dialog-test.js, tests/acceptance/tether-dialog-test.js, tests/dummy/app/app.js, tests/dummy/app/components/component-that-uses-modal-dialog.js, tests/dummy/app/controllers/application.js, tests/dummy/app/initializers/register-subclassed-modals.js, tests/dummy/app/router.js, tests/helpers/modal-asserts.js, tests/helpers/resolver.js, tests/helpers/start-app.js
- Update to ember-suave 1.2.3
- Use default ember-suave jscs preset
- Appease, appease, appease
=> Perform a big JSCS suave cleanup

index.js
This avoids the following deprecation warning:
DEPRECATION: Overriding init without calling this._super is deprecated.
Please call this._super.init && this._super.init.apply(this, arguments);
=> Call `this._super.init` to avoid ember-cli deprecation

package.json
This may be helpful for ember-cli builds as the `broccoli-filter` dependency will be swapped out for `broccoli-persistent-filter` as recommended in ember-cli's [peformance guide](https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md#a-2).
=> Bump ember-cli-htmlbars to 1.0.3

package.json
Pre 1.0 ember-cli-htmlbars does not use _super from init in a way that Ember likes.
=> Avoid deprecation warning by updating ember-cli-htmlbars

README.md
=> Update README to change usage of `ember-key-responder` to `ember-keyboard`

README.md, addon/services/modal-dialog.js, app/services/modal-dialog.js, tests/unit/services/modal-dialog-test.js
This commit maintains the previous behavior where the initializer appends the destination element to the DOM, but allows for falling back to the #ember-testing div in the testing environment.
This resolves #78 and resolves #125
=> Support unit and integration tests out of the box.

addon/components/modal-dialog.js, tests/.jshintrc, tests/acceptance/tether-dialog-test.js, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/-tether-dialog.hbs, tests/helpers/acceptance-helpers.js, tests/helpers/modal-asserts.js, tests/helpers/start-app.js
Prevents removal of the listener when multiple dialogs are on the same page.
This resolves an issue where multiple tether-dialogs without overlay and clickOutsideToClose would be available on the same page. Opening one and then directly open another would result in the handler `click.ember-modal-dialog` being removed and the new opened dialog would be without it.
=> Register unique clickOutsideToClose click handlers

index.js, package.json
Since ember introduced the ember-source from NPM, update API usage of ember-cli-version-checker.
=> Check for Ember version with new ember-cli-version-checker API.

README.md, addon/components/modal-dialog.js, addon/templates/current/components/modal-dialog.hbs, addon/templates/current/components/tether-dialog.hbs, addon/templates/lt-1-13/components/modal-dialog.hbs, addon/templates/lt-1-13/components/tether-dialog.hbs, tests/acceptance/modal-dialog-test.js, tests/acceptance/tether-dialog-test.js, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/-modal-dialog.hbs, tests/dummy/app/templates/-tether-dialog.hbs
This PR introduces a property for specifying a callback to be called when the overlay is clicked. This allows us to perform a different action than the default "close" action if necessary.
=> Add ability to specify a callback that is triggered when overlay is clicked.

app/styles/ember-modal-dialog/ember-modal-structure.scss, tests/acceptance/modal-dialog-test.js, tests/acceptance/tether-dialog-test.js
Relative was used for this, so if you were adjusting the relative positioning of your "rendered in place" modal dialog, you may need to make adjustments.
=> [BREAKING] Change default scss to use static positioning for render in place.

README.md, addon/components/modal-dialog.js, addon/templates/components/modal-dialog.hbs, addon/templates/components/tether-dialog.hbs, tests/acceptance/modal-dialog-test.js, tests/dummy/app/templates/-modal-dialog.hbs
`container-class` -> `containerClass`
`wrapper-class` -> `wrapperClass`
`overlay-class` -> `overlayClass`
=> Use camelCase properties, deprecate public kebab case properties

README.md, addon/components/modal-dialog.js, tests/dummy/app/templates/index.hbs, tests/dummy/app/templates/tether-dialog.hbs
- Support for `close` will be removed in 3.0.0
=> Rename `close` action to `onClose` and deprecate `close`.

addon/components/modal-dialog-overlay.js, addon/components/modal-dialog.js, addon/components/tether-dialog.js, addon/templates/components/modal-dialog.hbs, addon/templates/components/tether-dialog.hbs, package.json, yarn.lock
- `modal-dialog-overlay component` will be removed in 3.0.0.
- This will not affect most users as it is unusual to use this component directly.
=> Replace `modal-dialog-overlay` component with a div and deprecate it.

README.md, addon/components/basic-dialog.js, addon/components/deprecated-tether-dialog.js, addon/components/in-place-dialog.js, addon/components/tether-dialog.js, addon/templates/components/basic-dialog.hbs, addon/templates/components/deprecated-tether-dialog.hbs, addon/templates/components/in-place-dialog.hbs, addon/templates/components/modal-dialog.hbs, addon/templates/components/tether-dialog.hbs, app/components/ember-modal-dialog/-basic-dialog.js, app/components/ember-modal-dialog/-in-place-dialog.js, app/components/ember-modal-dialog/-tether-dialog.js, app/components/tether-dialog.js, app/templates/components/modal-dialog.js, app/templates/components/tether-dialog.js, tests/acceptance/basic-test.js, tests/acceptance/tether-dialog-test.js, tests/acceptance/tethered-test.js, tests/dummy/app/controllers/tethered.js, tests/dummy/app/router.js, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/tether-dialog.hbs, tests/dummy/app/templates/tethered.hbs
- chooses which strategy to use based on whether a `tetherTarget` property is passed
- `tether-dialog` component usage is deprecated and will be removed in 3.0.0 - switch to using `modal-dialog` and pass a `tetherTarget` property
- passing a `target` to `modal-dialog` is deprecated and positioning for non-tether will be 100% CSS in 3.0.0
- renderInPlace=true now renders without a wrapper div
=> Unify `modal-dialog` and `tether-dialog` into one `modal-dialog` component

README.md, addon/templates/components/basic-dialog.hbs, tests/acceptance/basic-test.js, tests/dummy/app/templates/index.hbs
- This already worked for the tethering code path.
=> Allow specifying `hasOverlay=false` to suppress output of the overlay div.

README.md, addon/components/basic-dialog.js, addon/components/modal-dialog.js, addon/templates/components/basic-dialog.hbs, addon/templates/components/modal-dialog.hbs, tests/acceptance/basic-test.js, tests/dummy/app/templates/index.hbs
- this property affects the relative DOM elements for non-tethered use cases
- `parent`, the default, uses a structure of:
```
wrapper
> overlay
> container
```
- `sibling`, uses a structure of: `wrapper > overlay > container`
```
wrapper
> overlay
> container
```
=> Add support for an `overlayPosition` property which supports values of `'parent'` or `'sibling'`

README.md, addon/components/basic-dialog.js, addon/components/deprecated-tether-dialog.js, addon/components/in-place-dialog.js, addon/components/liquid-dialog.js, addon/components/liquid-tether-dialog.js, addon/components/modal-dialog.js, addon/components/positioned-container.js, addon/templates/components/liquid-dialog.hbs, addon/templates/components/liquid-tether-dialog.hbs, app/components/ember-modal-dialog/-liquid-dialog.js, app/components/ember-modal-dialog/-liquid-tether-dialog.js, app/services/modal-dialog.js, app/styles/ember-modal-dialog/ember-modal-structure.scss, config/environment.js, package.json, tests/acceptance/animatable-test.js, tests/acceptance/basic-test.js, tests/acceptance/tethered-animatable-test.js, tests/dummy/app/controllers/animatable.js, tests/dummy/app/controllers/tethered-animatable.js, tests/dummy/app/router.js, tests/dummy/app/styles/app.scss, tests/dummy/app/templates/animatable.hbs, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/index.hbs, tests/dummy/app/templates/tethered-animatable.hbs, tests/dummy/app/transitions.js, yarn.lock
- To animate non-tethered cases, install `liquid-wormhole` and pass `animatable=true`
- To animate tethered cases, install `liquid-tether` and pass `animatable=true`
- See the dummy app for examples
- Note that in 3.0.0, the animatable code path will be used automatically if these libraries are present and `animatable` is unspecified. To prepare users for this, a deprecation warning is emitted if the libraries are present and `animatable` is unspecified in 2.x.
- targetAttachment of "center" and "middle center" now uses SCSS for positioning rather than dynamic rules
=> Make modal-dialog component animatable via liquid-fire

README.md
Added missing ',' to code sample regarding keyboard event handling.
=> Typo: missing comma

app/services/modal-dialog.js
- Hopefully restores working order in Ember Twiddle. Fixes #198.
=> Don't fail if ENV['ember-modal-dialog'] is not defined

README.md
let's prefer prefer `didInsertElement()` and `willDestroyElement()` over the .on() syntax
see: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-function-prototype-extensions.md
=> keyboard example - use Ember best practice form instead of .on()

.eslintrc.js, addon/components/basic-dialog.js, addon/components/deprecated-tether-dialog.js, addon/components/in-place-dialog.js, addon/components/liquid-tether-dialog.js, addon/components/modal-dialog-overlay.js, addon/components/modal-dialog.js, addon/components/positioned-container.js, addon/components/tether-dialog.js, app/services/modal-dialog.js, package.json, tests/acceptance/animatable-test.js, tests/acceptance/basic-test.js, tests/acceptance/tether-dialog-test.js, tests/acceptance/tethered-animatable-test.js, tests/acceptance/tethered-test.js, tests/dummy/app/app.js, tests/dummy/app/components/component-that-uses-modal-dialog.js, tests/dummy/app/controllers/animatable.js, tests/dummy/app/controllers/index.js, tests/dummy/app/controllers/tether-dialog.js, tests/dummy/app/controllers/tethered-animatable.js, tests/dummy/app/controllers/tethered.js, tests/dummy/app/router.js, tests/dummy/config/environment.js, tests/helpers/destroy-app.js, tests/helpers/modal-asserts.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, yarn.lock
Updates code to use the new modules API and enables an eslint rule to enforce it
=> use new modules api

package.json, yarn.lock
ember-cli-version-checker is `require`'d and used in `config/environment.js`, but it only worked because the package happened to be available via `ember-resolver`. We should list is as an explicit dependency.
=> Add ember-cli-version-checker as a dep

addon/components/basic-dialog.js
closes #195 
This issue affects IE 11 which is still being supported for quite some time. It seems somehow to be related to https://github.com/emberjs/ember.js/issues/14264 , though that particular issue was fixed. @PrzemoRevolve found a work around, but instead of adding empty strings for the concatenated properties every time modal-dialog is used, the work around can be implemented inside basic-dialog.js by adding default values of empty arrays to those properties.
@lukemelia this works on IE 11, <strike>do you think it will cause any unwanted side effects?</strike> with null values instead of empty arrays (which I tried first) I don't think it should cause any side effects.
=> fix(#195): provide default values for concatenatedProperties

app/services/modal-dialog.js
https://github.com/yapplabs/ember-modal-dialog/issues/231 raised an issue with the changes I made in https://github.com/yapplabs/ember-modal-dialog/pull/215.  I _should not_ have updated any files in /app since those are transpiled by the consuming app which would require them to be on ember-cli-babel 6.6 or greater.  This commit reverts that change to avoid any breaking changes for consumers of this addon who have not updated their ember-cli-babel yet.
=> Revert modules update to file in app directory

.travis.yml, addon/components/basic-dialog.js
This bug prevented closing the modal when a stack was specified and click target was within the modal of a separate stack.
=> Fix bug with clickOutsideToClose when specifying a stack

README.md
Are you sure that this sentence is valid? One line above we can see that animatable option requires additional dependencies.
=> Confusing sentence

.eslintrc.js, addon/components/basic-dialog.js, addon/components/deprecated-tether-dialog.js, addon/components/positioned-container.js, tests/acceptance/animatable-test.js, tests/acceptance/basic-test.js, tests/acceptance/tether-dialog-test.js, tests/acceptance/tethered-animatable-test.js, tests/acceptance/tethered-test.js, tests/dummy/app/controllers/animatable.js, tests/dummy/app/controllers/index.js, tests/dummy/app/controllers/tethered-animatable.js, tests/helpers/modal-asserts.js
=> Removing jQuery

addon/components/basic-dialog.js
Fixes failed tests since ember 3.2.
Based on tips from this issue https://github.com/emberjs/ember.js/issues/16778
=> Don't sendAction in click handler when component isDestroying or isDestroyed

README.md
A `full-screen-modal` component that subclasses `modal-dialog` will not display correctly if it has a template file.
=> update README.md Custom Modals section

addon/initializers/add-modals-container.js
Hi there!
It turns out that it's possible for rootElement to be a node rather than an id. An example is when running Storybook, but there are likely others. This makes sure that doesn't fail.
=> Handle when App.rootElement can be a node, rather than an id

README.md, addon/components/basic-dialog.js, addon/components/modal-dialog.js, tests/dummy/app/templates/animatable.hbs, tests/dummy/app/templates/index.hbs, tests/dummy/app/templates/tethered-animatable.hbs, tests/dummy/app/templates/tethered.hbs
=> use closure actions

package.json, yarn.lock
In preparation for the 3.0.0 release, I thought it would be a good idea to update to ember-cli-babel@7. No additional changes should be required, and the only breaking changes in ember-cli-babel@7 are:
* Drop support for Node < 6.
* Drop support for ember-cli < 2.13.
=> Update to ember-cli-babel@7.

CONTRIBUTING.md, README.md
The purpose of thir PR is to move contribution instructions to `CONTRIBUTING.md`
=> Move contribution guide to CONTRIBUTING.md

README.md
Removes the '.css' extension from the css @import links
the user is told to paste into app.css, which produce 404 errors in
a fresh install.
=> fixes bad css import snippet in README installation instructions

README.md
There are two places in the README where the user is told how to install CSS.
The first place is more of a quick start guide and only shows how to import
using regular CSS. The second place shows how to import both CSS and SASS.
As a SASS user installing the addon it is easy to not notice the second section and get tripped up
and use the CSS imports instead of the SASS imports, as I did, and never notice the second section in the README.
This commit reverts an earlier change I made and copies the SASS instructions to
the Quickstart section.
=> fixes my previous change to the css installation instructions

addon/components/modal-dialog.js
I accidentally gave callback as a string rather than function, the app broke, I think its good to check action type is a function before calling it
=> check type function for action callbacks

addon/components/basic-dialog.js
In Ember tests, because the handleClick is registered inside a 'setTimeout' (which is not subject to wait()/settled()), it is possible for the addEventListener to happen AFTER the willDestroy/removeEventListener; leading to blowups in the handleClick (destroyed component).
This can lead to test blowups that are very hard to track down (since they appear to occur randomly in a later test).  A simple isDestroyed test works wonders.
Backported from commit 2d83a7afc0ef68d7abfa65891ea4a0fbb0e5fa89
=> Backport isDestroying check in handleClick (from 2d83a7af)

addon/initializers/add-modals-container.js
This should resolve https://github.com/yapplabs/ember-modal-dialog/issues/320 while https://github.com/emberjs/ember.js/issues/19532 is not fixed yet, and should unblock Ember upgrades for users of this addon :)
/cc @lukemelia @romgere
=> initializers/add-modals-container: Work around string injection bug

addon/components/basic-dialog.js, addon/components/liquid-tether-dialog.js, addon/components/modal-dialog.js, addon/components/positioned-container.js, addon/components/tether-dialog.js
see https://blog.emberjs.com/ember-3-1-beta-released/#toc_es5-getters-for-computed-properties
This will probably require us to bump the minimum supported Ember version though, but since v3.1 was released over three years ago (😱), I guess that is fine by now?
=> Remove obsolete `this.get(...)` calls

.eslintrc.js, README.md, addon/components/basic-dialog.js, addon/components/in-place-dialog.js, addon/components/liquid-dialog.js, addon/components/liquid-tether-dialog.js, addon/components/modal-dialog.js, addon/components/tether-dialog.js, package.json, tests/dummy/app/components/component-that-uses-modal-dialog.js, tests/dummy/app/components/my-cool-modal-dialog.js, tests/dummy/app/controllers/animatable.js, tests/dummy/app/controllers/index.js, tests/dummy/app/controllers/tethered-animatable.js, tests/dummy/app/controllers/tethered.js, yarn.lock
This PR removes ember-classic-decorator and refactors `this.get` and `this.set` to use `Ember.get` and `Ember.set`. This was necessary because ember-classic-decorator was using global Ember.
=> Remove ember-classic-decorator

package.json
This should help with embroider issues. Embroider does not like when there are imports from a package that is not a dependency of some kind.
=> Add ember-tether as a peerDependency

addon/components/in-place-dialog.js, addon/templates/components/basic-dialog.hbs, addon/templates/components/in-place-dialog.hbs, addon/templates/components/liquid-dialog.hbs, addon/templates/components/liquid-tether-dialog.hbs, addon/templates/components/modal-dialog.hbs, addon/templates/components/tether-dialog.hbs, tests/acceptance/basic-test.js, tests/dummy/app/templates/index.hbs, tests/helpers/modal-asserts.js
containerClassNames are not passed to the rendered in place modal.
Or rather the property is overriden by the component.
This PR allows us to have rendered in place modals take in the containerClassNames property
=> Add splattibutes support and fix containerClassNames for rendered in place modals

.eslintrc.js, addon/utils/config-utils.js
Fixes #399
Would be nice to have a Fastboot test suite but I don't think it needs to block this fix.
I did a naive test by logging the `globalThis` object to make sure it's present in a Fastboot execution – it is.
=> Avoid Fastboot crash when accessing `navigator` global

addon/components/basic-dialog.hbs, addon/components/liquid-dialog.hbs, tests/dummy/app/utils/code-snippets/index.js
Ember `5.x` [deprecated the `{{action}}` helper](https://deprecations.emberjs.com/id/template-action). By removing the uses in `addon`, we can separate why `ember-release`, `ember-beta`, and `ember-canary` (all now point to `6.x`) currently fail.
I followed the migration guides in the deprecation page:
> Scenario: `action` is passed a function reference
>
> Before:
>
> ```hbs
> <SomeComponent @update={{action this.plusOne}} />
> ```
>
> After:
>
> ```hbs
> <SomeComponent @update={{this.plusOne}} />
> ```
The number of failing tests in `ember-release` is down from 19 to 8, and I believe this PR will be my last one.
<details>
<summary>Before: Test results from <code>ember-release</code> scenario</summary>
```sh
❯ pnpm test:ember-compatibility ember-release --- pnpm test
devDependencies:
- …
```
=> Removed {{action}} helper from addon
